# Generated by Django 2.0.5 on 2018-12-13 18:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBXInfo',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=10)),
                ('area', models.CharField(choices=[('n', '北海'), ('e', '东海'), ('s', '南海')], max_length=2, verbose_name='所属海区')),
                ('desc', models.CharField(max_length=200, verbose_name='描述信息')),
                ('shipton', models.FloatField(default=100, max_length=4, verbose_name='吨位-单位百万')),
                ('shiptype', models.CharField(choices=[('s', '小型'), ('m', '中型'), ('l', '大型')], max_length=2, verbose_name='船型')),
                ('sort', models.IntegerField(default=99, verbose_name='排序')),
            ],
            options={
                'verbose_name': '船舶基础信息',
                'verbose_name_plural': '船舶基础信息',
            },
        ),
        migrations.CreateModel(
            name='BBXSpaceInfo',
            fields=[
                ('bsid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=10)),
                ('nowdate', models.DateTimeField(default=datetime.datetime.now)),
                ('lat', models.FloatField(max_length=6, verbose_name='经度')),
                ('lon', models.FloatField(max_length=6, verbose_name='维度')),
                ('heading', models.FloatField(null=True, verbose_name='船首向')),
                ('speed', models.FloatField(null=True, verbose_name='速度')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbx.BBXInfo')),
            ],
            options={
                'verbose_name': '船舶基础数据（空间信息）',
                'verbose_name_plural': '船舶基础数据（空间信息）',
            },
        ),
        migrations.CreateModel(
            name='BBXSpaceTempInfo',
            fields=[
                ('bsid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=10)),
                ('nowdate', models.DateTimeField(default=datetime.datetime.now)),
                ('lat', models.FloatField(max_length=6, verbose_name='经度')),
                ('lon', models.FloatField(max_length=6, verbose_name='维度')),
                ('heading', models.FloatField(null=True, verbose_name='船首向')),
                ('speed', models.FloatField(null=True, verbose_name='速度')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbx.BBXInfo')),
            ],
            options={
                'verbose_name': '船舶基础数据（临时表）',
                'verbose_name_plural': '船舶基础数据（临时表）',
            },
        ),
        migrations.CreateModel(
            name='HydrologyData',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('wt', models.FloatField(max_length=4, null=True, verbose_name='水温')),
                ('wvs', models.FloatField(max_length=4, null=True, verbose_name='浪向')),
                ('wv', models.FloatField(max_length=4, null=True, verbose_name='浪高')),
                ('surge1d', models.FloatField(max_length=4, null=True, verbose_name='第一组涌向')),
                ('surge1c', models.FloatField(max_length=4, null=True, verbose_name='第一组涌周期')),
                ('surge1h', models.FloatField(max_length=4, null=True, verbose_name='第一组涌高')),
                ('surge2d', models.FloatField(max_length=4, null=True, verbose_name='第二组涌向')),
                ('surge2c', models.FloatField(max_length=4, null=True, verbose_name='第二组涌周期')),
                ('surge2h', models.FloatField(max_length=4, null=True, verbose_name='第二组涌向')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbx.BBXInfo')),
            ],
            options={
                'verbose_name': '水文要素历史表',
                'verbose_name_plural': '水文要素历史表',
            },
        ),
        migrations.CreateModel(
            name='MeteorologicalData',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间戳')),
                ('rain', models.FloatField(max_length=10, null=True, verbose_name='降水')),
                ('vis', models.FloatField(max_length=10, null=True, verbose_name='能见度')),
                ('cloudc', models.FloatField(max_length=10, null=True, verbose_name='云量')),
                ('wd', models.FloatField(max_length=10, null=True, verbose_name='风向')),
                ('ws', models.FloatField(max_length=10, null=True, verbose_name='风速')),
                ('cwd', models.FloatField(max_length=10, null=True, verbose_name='最大风向')),
                ('cws', models.FloatField(max_length=10, null=True, verbose_name='最大风速')),
                ('at', models.FloatField(max_length=4, null=True, verbose_name='气温')),
                ('dpt', models.FloatField(max_length=10, null=True, verbose_name='露点温度')),
                ('bp', models.FloatField(max_length=10, null=True, verbose_name='气压')),
                ('wetnow', models.FloatField(max_length=10, null=True, verbose_name='当前湿度')),
                ('wet1', models.FloatField(max_length=10, null=True, verbose_name='湿度1')),
                ('wet2', models.FloatField(max_length=10, null=True, verbose_name='湿度2')),
                ('cloudlc', models.FloatField(max_length=10, null=True, verbose_name='云总量')),
                ('clouds', models.FloatField(max_length=10, null=True, verbose_name='云状')),
                ('cloudms', models.FloatField(max_length=10, null=True, verbose_name='')),
                ('cloudhs', models.FloatField(max_length=10, null=True, verbose_name='云高')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbx.BBXInfo')),
            ],
            options={
                'verbose_name': '气象要素',
                'verbose_name_plural': '气象要素',
            },
        ),
        migrations.CreateModel(
            name='RealtimeData',
            fields=[
                ('rdid', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间戳')),
                ('rain', models.FloatField(max_length=10, null=True, verbose_name='降水')),
                ('vis', models.FloatField(max_length=10, null=True, verbose_name='能见度')),
                ('cloudc', models.FloatField(max_length=10, null=True, verbose_name='云量')),
                ('wd', models.FloatField(max_length=10, null=True, verbose_name='风向')),
                ('ws', models.FloatField(max_length=10, null=True, verbose_name='风速')),
                ('cwd', models.FloatField(max_length=10, null=True, verbose_name='最大风向')),
                ('cws', models.FloatField(max_length=10, null=True, verbose_name='最大风速')),
                ('at', models.FloatField(max_length=4, null=True, verbose_name='气温')),
                ('dpt', models.FloatField(max_length=10, null=True, verbose_name='露点温度')),
                ('bp', models.FloatField(max_length=10, null=True, verbose_name='气压')),
                ('wetnow', models.FloatField(max_length=10, null=True, verbose_name='当前湿度')),
                ('wet1', models.FloatField(max_length=10, null=True, verbose_name='湿度1')),
                ('wet2', models.FloatField(max_length=10, null=True, verbose_name='湿度2')),
                ('cloudlc', models.FloatField(max_length=10, null=True, verbose_name='云总量')),
                ('clouds', models.FloatField(max_length=10, null=True, verbose_name='云状')),
                ('cloudms', models.FloatField(max_length=10, null=True, verbose_name='')),
                ('cloudhs', models.FloatField(max_length=10, null=True, verbose_name='云高')),
                ('wt', models.FloatField(max_length=4, null=True, verbose_name='水温')),
                ('wvs', models.FloatField(max_length=4, null=True, verbose_name='浪向')),
                ('wv', models.FloatField(max_length=4, null=True, verbose_name='浪高')),
                ('surge1d', models.FloatField(max_length=4, null=True, verbose_name='第一组涌向')),
                ('surge1c', models.FloatField(max_length=4, null=True, verbose_name='第一组涌周期')),
                ('surge1h', models.FloatField(max_length=4, null=True, verbose_name='第一组涌高')),
                ('surge2d', models.FloatField(max_length=4, null=True, verbose_name='第二组涌向')),
                ('surge2c', models.FloatField(max_length=4, null=True, verbose_name='第二组涌周期')),
                ('surge2h', models.FloatField(max_length=4, null=True, verbose_name='第二组涌向')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbx.BBXInfo')),
            ],
            options={
                'verbose_name': '志愿船的水文气象要素（临时表）',
                'verbose_name_plural': '志愿船的水文气象要素（临时表）',
            },
        ),
    ]
